{{- if $.Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "spark-operator.fullname" . }}-pdb
  labels:
    {{- include "spark-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "spark-operator.selectorLabels" . | nindent 6 }}
  minAvailable: {{ $.Values.pdb.minAvailable }}
{{- end }}
