apiVersion: sparkoperator.k8s.io/v1alpha1
kind: SparkConnect
metadata:
  name: spark-connect-ingress-example
  namespace: default
spec:
  sparkVersion: "4.0.1"
  image: docker.io/library/spark:4.0.1
  server:
    cores: 1
    memory: "512m"
    service:
      type: ClusterIP
    ingress:
      metadata:
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /
          kubernetes.io/ingress.class: nginx
      spec:
        rules:
        - host: spark-connect.example.com
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: spark-connect-ingress-example-server
                  port:
                    number: 15002
  executor:
    cores: 1
    memory: "512m"
    instances: 1